name: Main Script Automation

on:
  schedule:
    - cron: '*/1 * * * *'  # Запуск кожні 5 хвилин
  workflow_dispatch:  # Можливість запускати вручну

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python api/another/main.py
