name: Automated tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repositiry
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Chtome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: attrs==24.2.0
        run: certifi==2024.8.30
        run: charset-normalizer==3.4.0
        run: colorama==0.4.6
        run: exceptiongroup==1.2.2
        run: idna==3.10
        run: iniconfig==2.0.0
        run: Jinja2==3.1.4
        run: jsonschema==4.23.0
        run: jsonschema-path==0.3.3
        run: jsonschema-specifications==2023.12.1
        run: lazy-object-proxy==1.10.0
        run: MarkupSafe==3.0.2
        run: openapi-schema-validator==0.6.2
        run: openapi-spec-validator==0.7.1
        run: packaging==24.1
        run: pathable==0.4.3
        run: pluggy==1.5.0
        run: pyrsistent==0.20.0
        run: pytest==8.3.3
        run: PyYAML==6.0.2
        run: referencing==0.35.1
        run: requests==2.32.3
        run: rfc3339-validator==0.1.4
        run: rpds-py==0.20.0
        run: six==1.16.0
        run: swagger-unittest==0.3.6
        run: tomli==2.0.2
        run: urllib3==2.2.3
        run: Werkzeug==3.0.4

      - name: Run tests
        run: pytest




