name: Automated tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repositiry
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Chtome
        run: sudo apt-get install google-chrome-stable
      - name: upgrade pip
        run: python -m pip install --upgrade pip 
      - name: install reques
        run: pip install -r requirements.txt
      - name: Run tests
        run: print("testtest")




